language: generic
sudo: require
services:
  - docker
before_install:
  - docker build -t chendykeo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chendykeo/docker-react npm run test -- --coverage