FROM node:alpine

ENV HTTP_PROXY="http://cdhwg01.prod.prv:80"
ENV HTTPS_PROXY="http://cdhwg01.prod.prv:80"

WORKDIR '/app'

COPY package.json .
# RUN npm config set registry http://registry.npmjs.org/
RUN npm install

COPY . .

CMD ["npm", "run", "start"]